# Generated by Django 5.0.1 on 2024-03-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='option',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.AlterField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='htmlwebsite.poll'),
        ),
    ]
