# Generated by Django 5.0.1 on 2024-03-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0004_rename_text_option_option_remove_option_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
