# Generated by Django 5.0.1 on 2024-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0009_remove_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
