# Generated by Django 4.2.8 on 2024-04-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0010_remove_choice_question_choice_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='htmlwebsite.question'),
            preserve_default=False,
        ),
    ]
