# Generated by Django 4.2.8 on 2024-04-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0011_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_text1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text4',
        ),
    ]
