# Generated by Django 4.2.8 on 2024-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0012_remove_question_choice_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
